version: "3.2"

services:
  backend:
    image:
      balthify-backend:2
    environment:
      BALTHIFY2_DB_URL: sqlite+aiosqlite:////opt/balthify2/data/testing.db
      BALTHIFY2_ACL_LOOKUP_URL: http://backend/schedule/lookup
      BALTHIFY2_ACL_REDIRECT_DOMAIN: 127.0.0.1
    networks:
      - common
    volumes:
      - backend-data:/opt/balthify2/data
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
  tgbot:
    image:
      balthify-tgbot:2
    environment:
      BALTHIFY2_TGBOT_JSON_PATH: /run/secrets/balthify2_tgbot_tokens_and_ids_json
      BALTHIFY2_TGBOT_INGRESS_APP: publish
      BALTHIFY2_TGBOT_EGRESS_APP: play
      BALTHIFY2_TGBOT_SCHEDULE_API_URL: http://backend/schedule/
      BALTHIFY2_TGBOT_DATASERVER_BASE_URL: rtmp://rtmp.example.com/
    networks:
      - common
    deploy:
      mode: replicated
      replicas: 1
    secrets:
      - balthify2_tgbot_tokens_and_ids_json
  nginx:
    image:
      balthify-nginx:2
    ports:
      - 8080:80
      - 1935:1935
    networks:
      - common
      - frontend
    deploy:
      mode: replicated
      replicas: 1

volumes:
  backend-data:

networks:
  common:
    driver: overlay
    ipam:
      config:
        - subnet: 10.xx.0.0/24
  frontend:
    driver: overlay
    ipam:
      config:
        - subnet: 10.xx.1.0/24

secrets:
  balthify2_tgbot_tokens_and_ids_json:
    external: true
